---
name: Weather-Underground-StationHistory
version: 1.0.2
author:
  - 'Elliot Shank <perl@galumph.com>'
abstract: Utility functions for dealing with weather station historical data from http://wunderground.com.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Regexp::Common: 0
  version: 0
build_requires:
  File::Find::Rule: 0
  Test::More: 0
  version: 0
recommends:
  File::Slurp: 0
  Perl::Critic: 0
  Pod::Coverage::CountParents: 0
  Test::Differences: 0
  Test::Distribution: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
dynamic_config: 1
provides:
  Weather::Underground::StationHistory:
    file: lib/Weather/Underground/StationHistory.pm
    version: 1.0.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
